wdls/main/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp, Required
from flask_pagedown.fields import PageDownField
from flask_ckeditor import CKEditor, CKEditorField


class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0, 64)]) 
    location = StringField('Location', validators=[Length(0, 64)]) 
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    body = CKEditorField("What's on your mind now? (Use Markdown text.)", validators=[Required()])
    submit = SubmitField('Submit')


class GeneralForm(FlaskForm):
    input = StringField('id', validators=[Length(0, 64)])
    submit = SubmitField('Submit')

wdls/__init__.py
# -*- coding: utf-8 -*-

import os
import time
from os import environ
from sqlite3 import dbapi2 as sqlite3
from flask import Flask, request, session, g, redirect, url_for, abort, \
     render_template, flash
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config
from auth import login_manager
from models import db, User
from flask_moment import Moment
from flask_pagedown import PageDown
from flask_ckeditor import CKEditor

# from flask_login import UserMixin
# from flask_login import login_user
# from flask_login import logout_user
# from wtforms import Form, BooleanField, TextField, PasswordField, validators

from .main import main as main_blueprint
from .auth import auth as auth_blueprint

from .api_1_0 import api as api_1_0_blueprint


# create our application :)

bootstrap = Bootstrap()
moment = Moment()
pagedown = PageDown()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    login_manager.init_app(app)
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    pagedown.init_app(app)
    with app.app_context():
        db.create_all()
        db.session.commit()

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    app.config.from_envvar('FLASKR_SETTINGS', silent=True)

    ckeditor = CKEditor(app)
    return app

wdls/api_1_0/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

api = Blueprint('api', __name__)

from . import authentication, errors
#  posts, users, comments, 

wdls/main/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

wdls/main/views.py
# -*- coding: utf-8 -*-
import os
import time
import urllib
import hashlib
import requests
import xml.etree.ElementTree as ET

from .. import constants
from time import time
from ..utinity import utinity, zhihu
from datetime import datetime
from flask import render_template, redirect, url_for, flash, request, abort, current_app, make_response
from . import main
from ..models import Entries, db, User, Post
from .forms import EditProfileForm, PostForm, GeneralForm
from flask_login import login_required, current_user
from flask_moment import Moment


@main.route('/')
@main.route('/home')
def show_entries():
    entry = db.session.query(Entries.id, Entries.title, Entries.text, Entries.times, User.username, Entries.author_id).\
        filter(Entries.author_id == User.id).order_by(Entries.times.desc()).all()
    entries = [dict(id=row.id, title=row.title, text=row.text, times=row.times, author=row.username, author_id=row.author_id) for row in entry]
    return render_template('show_entries.html', entries=entries)


@main.route('/delete', methods=['POST'])
@login_required
def delete_entry():
    id = request.form['entry_id']
    user_entry = Entries.query.filter_by(id=id).first()
    if int(user_entry.author_id) != int(current_user.get_id()):
        flash('You can not delete entry not belongs to you')
        return redirect(url_for('main.show_entries'))
    Entries.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('main.show_entries'))


@main.route('/add', methods=['POST'])
@login_required
def add_entry():
    if request.form['title'] == "" or request.form['text'] == "":
        flash('empty is illegal')
        return redirect(url_for('main.show_entries'))
    new_entry = Entries(title=request.form['title'],
                        text=request.form['text'],
                        times=datetime.utcnow(),
                        author_id=current_user.get_id())
    db.session.add(new_entry)
    db.session.commit()
    flash('New entry was successfully posted')
    return redirect(url_for('main.show_entries'))


@main.route('/user/<username>', methods=['GET', 'POST'])
def user(username):
    username = utinity.convert_url_uni(username)
    form = PostForm()
    user = User.query.filter_by(username=username).first()
    if user is None:
        return abort(404)
    if hasattr(current_user, 'username') and current_user.username == username and \
            form.validate_on_submit():
        post = Post(body=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('main.user', username=username))
    # posts = user.posts.order_by(Post.timestamp.desc()).all()

    page = request.args.get('page', 1, type=int)
    pagination = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('user.html', user=user, form=form, posts=posts, pagination=pagination)


@main.route('/edit-profile', methods=['GET', 'POST']) 
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)


@main.route('/post/<username>', methods=['GET', 'POST'])
def post(username):
    username = utinity.convert_url_uni(username)
    form = PostForm()
    if current_user.username == username and \
            form.validate_on_submit():
        post = Post(body=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('post.html', form=form, posts=posts)


@main.route('/<username>/delete', methods=['POST'])
@login_required
def delete_post(username):
    username = utinity.convert_url_uni(username)
    id = request.form['post_id']
    post = Post.query.filter_by(id=id).first()
    if int(post.author_id) != int(current_user.get_id()):
        flash('You can not delete entry not belongs to you')
        return redirect(url_for('main.user', username=username))
    Post.query.filter_by(id=id).delete()
    db.session.commit()
    flash('Your post has been deleted successfully.')
    return redirect(url_for('main.user', username=current_user.username))


@main.route('/follow/<username>')
@login_required
def follow(username):
    username = utinity.convert_url_uni(username)
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('main.show_entries'))
    if current_user.is_following(user):
        flash('You have already followed this user.')
        return redirect(url_for('.user', username=username))
    current_user.follow(user)
    flash('You are now following %s.' % username)
    return redirect(url_for('.user', username=username))


@main.route('/unfollow/<username>')
@login_required
def unfollow(username):
    username = utinity.convert_url_uni(username)
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('main.show_entries'))
    if not current_user.is_following(user):
        flash('You are not following this user.')
        return redirect(url_for('.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following %s anymore.' % username)
    return redirect(url_for('.user', username=username))


@main.route('/followers/<username>')
def followers(username):
    username = utinity.convert_url_uni(username)
    user = User.query.filter_by(username=username).first() 
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('main.show_entries'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
                for item in pagination.items]
    return render_template('followers.html', user=user, title="Followers of",
                        endpoint='.followers', pagination=pagination,
                        follows=follows)


@main.route('/followed_by/<username>')
def followed_by(username):
    username = utinity.convert_url_uni(username)
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template('followers.html', user=user, title="Followed by",
                           endpoint='.followed_by', pagination=pagination,
                           follows=follows)


@main.route('/all_users')
def all_users():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    users = pagination.items

    return render_template('all_users.html', users=users, title='All users',
                           endpoint='.all_users', pagination=pagination)


@main.route('/zhihu_id', methods=['GET', 'POST'])
def zhihu_id():
    form = GeneralForm()
    qid = form.input.data
    if form.validate_on_submit():
        qid = form.input.data
        url_list = zhihu.get_image_url(qid)
        if url_list is not None:
            return render_template('zhihu.html', endpoint='.zhihu_id', url_list=url_list, qid=qid)
        return redirect(url_for('main.zhihu_id'))
    return render_template('zhihu_id.html', form=form)
    

@main.route('/wechat',methods=['GET','POST'])
def wechat():
    if request.method == 'GET':
        #这里改写你在微信公众平台里输入的token
        token = 'shengtokentoken'
        #获取输入参数
        data = request.args
        signature = data.get('signature','')
        timestamp = data.get('timestamp','')
        nonce = data.get('nonce','')
        echostr = data.get('echostr','')
        #字典排序
        list = [token, timestamp, nonce]
        list.sort()

        s = list[0] + list[1] + list[2]
        #sha1加密算法        
        hascode = hashlib.sha1(s.encode('utf-8')).hexdigest()
        #如果是来自微信的请求，则回复echostr
        if hascode == signature:
            return echostr
        else:
            return ""

    if request.method == "POST":
        token = "1qup6gDhS2U.cwA.82g.JfcKFDfVXSg5ixHisrCJHz-x7nsLakSBlcNz0nCkRLQ"
        rec=request.stream.read()
        parser = ET.XMLParser(encoding="utf-8")
        xml_rec = ET.fromstring(rec, parser=parser)
        ToUserName = xml_rec.find('ToUserName').text
        fromUser = xml_rec.find('FromUserName').text
        MsgType = xml_rec.find('MsgType').text
        Content = xml_rec.find('Content').text
        #MsgId = xml_rec.find('MsgId').text

        reply = """<xml>
                  <ToUserName> <![CDATA[%s]]></ToUserName>
                  <FromUserName><![CDATA[%s]]></FromUserName>
                  <CreateTime>%s</CreateTime>
                  <MsgType><![CDATA[text]]></MsgType>
                  <Content><![CDATA[%s]]></Content>
                  </xml>"""

        # Start conversation

wdls/utinity/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/4/1 下午1:36
# @Author  : Aries
# @Site    : 
# @File    : __init__.py.py
# @Software: PyCharm

wdls/views.py
# -*- coding: utf-8 -*-

from datetime import datetime
from flask import render_template
import os
import time
from os import environ
from sqlite3 import dbapi2 as sqlite3
from flask import current_app, request, session, g, redirect, url_for, abort, \
     render_template, flash
from wtforms import Form, BooleanField, TextField, PasswordField, validators, StringField


time_format = '%Y-%m-%d %X'
app = current_app


@app.route('/login1', methods=['GET', 'POST'])
def login1():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        cur = g.db.execute('select id, name, password, email from users')
        find = 0
        for row in cur.fetchall():
            if row[1] == username:
                find = 1
                id = row[0]
                true_password = row[2]
                break
        if find == 1:
            if password == true_password:
                curr_user = User()
                curr_user.id = id
                next = request.args.get('next')
                return redirect(next or url_for('show_entries'))
        flash('Wrong username or password')
        return render_template('login1.html')
    else:
        return render_template('login1.html')

    #
    #
    # user = User.objects(name=username,
    #                     password=password).first()
    # if user:
    #     login_user(user)
    #     return jsonify(user.to_json())
    # else:
    #     return jsonify({"status": 401,
    #                     "reason": "Username or Password Error"})
    #


def query_user(id):
    cur = g.db.execute('select id from users')
    if len(cur.fetchall()) != 0:
        id = cur.fetchall()[0][0]
    else:
        id = -1
    return id


#
# @login_manager.user_loader
# def load_user(user_id):
#     if query_user(user_id) != -1:
#         curr_user = User()
#         curr_user.id = user_id
#         return curr_user
#


def connect_db():
    return sqlite3.connect(app.config['DATABASE'])
    rv.row_factory = sqlite3.Row
    return rv


def get_db():
    """Opens a new database connection if there is none yet for the
    current application context.
    """
    if not hasattr(g, 'sqlite_db'):
        g.sqlite_db = connect_db()
    return g.sqlite_db


@app.teardown_appcontext
def close_db(error):
    """Closes the database again at the end of the request."""
    # use with get_db
    if hasattr(g, 'sqlite_db'):
        g.sqlite_db.close()


def init_db():
    db = get_db()
    with app.open_resource('schema.sql', mode='r') as f:

        db.cursor().executescript(f.read())
    db.commit()

#
# @app.cli.command('initdb')
# def initdb_command():
#     """Initializes the database."""
#     init_db()
#     print 'Initialized the database.'


@app.route('/')
@app.route('/home')
def show_entries():
    cur = g.db.execute('select id, title, text, times from entries order by id desc')
    # print cur.fetchall()
    entries = [dict(id=row[0], title=row[1], text=row[2], times=row[3]) for row in cur.fetchall()]
    return render_template('show_entries.html', entries=entries)


@app.route('/user_entries')
def show_user_entries():
    cur = g.db.execute('select id, title, text, times from user_entries order by id desc')
    # print cur.fetchall()
    entries = [dict(id=row[0], title=row[1], text=row[2], times=row[3]) for row in cur.fetchall()]
    return render_template('show_entries.html', entries=entries)


@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        if request.form['username'] != app.config['USERNAME']:
            error = 'Invalid username'
        elif request.form['password'] != app.config['PASSWORD']:
            error = 'Invalid password'
        else:
            session['logged_in'] = True
            flash('You were logged in')
            return redirect(url_for('show_entries'))
    return render_template('login.html', error=error)


@app.route('/sign_in', methods=['GET', 'POST'])
def sign_in():
    return redirect(url_for('show_entries'))


@app.before_request
def before_request():
    g.db = connect_db()

wdls/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

wdls/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

wdls/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=post.author.username) }}">{{ post.author.username }}</a></div>
            <div class="post-body">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            </div>
            <div class="post-footer">
                {% if current_user == post.author %}
                <a href="{{ url_for('.edit', id=post.id) }}">
                    <span class="label label-primary">Edit</span>
                </a>
                {% elif current_user.is_administrator() %}
                <a href="{{ url_for('.edit', id=post.id) }}">
                    <span class="label label-danger">Edit [Admin]</span>
                </a>
                {% endif %}
                <a href="{{ url_for('.post', id=post.id) }}">
                    <span class="label label-default">Permalink</span>
                </a>
                <a href="{{ url_for('.post', id=post.id) }}#comments">
                    <span class="label label-primary">{{ post.comments.count() }} Comments</span>
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

wdls/templates/all_users.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Web - {{ title }} {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ title }}</h1>
</div>
<table class="table table-hover followers">
    <thead><tr><th>User</th><th>Name</th></tr></thead>
    {% for user in users %}
    <tr>
        <td>
            <a href="{{ url_for('.user', username = user.username) }}">
                <img class="img-rounded" src="{{ user.gravatar(size=32) }}">
                {{ user.username }}
            </a>
        </td>
        <td>{{ user.name }}</td>
    </tr>
    {% endfor %}
</table>
<div class="pagination">
    {{ macros.pagination_widget(pagination, endpoint) }}
</div>
{% endblock %}

wdls/templates/base.html
{% extends "bootstrap/base.html" %}
{{ moment.include_moment() }}
{% block title %}Web{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.show_entries') }}">Web</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <li><a href="{{ url_for('main.show_entries') }}">Public Hall</a></li>
                <li><a href="{{ url_for('main.all_users') }}">All Users</a></li>
                <li><a href="{{ url_for('main.zhihu_id') }}">Search Zhihu</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ current_user.gravatar(size=18) }}">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('main.user', username=current_user.username) }}">Me</a></li>
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Change Email(Not implemented)</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

wdls/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

wdls/templates/followers.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Web - {{ title }} {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ title }} {{ user.username }}</h1>
</div>
<table class="table table-hover followers">
    <thead><tr><th>User</th><th>Since</th></tr></thead>
    {% for follow in follows %}
    {% if follow.user != user %}
    <tr>
        <td>
            <a href="{{ url_for('.user', username = follow.user.username) }}">
                <img class="img-rounded" src="{{ follow.user.gravatar(size=32) }}">
                {{ follow.user.username }}
            </a>
        </td>
        <td>{{ moment(follow.timestamp).format('L') }}</td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
<div class="pagination">
    {{ macros.pagination_widget(pagination, endpoint, username = user.username) }}
</div>
{% endblock %}

wdls/templates/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
{% block title %}User - {{ user.username }}{% endblock %}

    <div class="page-header">
        <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}">
        <div class="profile-header">
        <h1>{{ user.username }}</h1>
        {% if user.name or user.location %}
            <p>
                {% if user.name %}{{ user.name }}{% endif %}
                    <br>
                    <font size="4">From</font>
                    {% if user.location %}
                    {{ user.location }}
                {% endif %} 
            </p>
        {% endif %}
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        <p>{{ user.posts.count() }} posts. {{ user.comments.count() }} comments.</p>

        <p>
                {% if current_user.is_authenticated and user != current_user %}
                    {% if not current_user.is_following(user) %}
                    <a href="{{ url_for('.follow', username=user.username) }}" class="btn btn-primary">Follow</a>
                    {% else %}
                    <a href="{{ url_for('.unfollow', username=user.username) }}" class="btn btn-default">Unfollow</a>
                    {% endif %}
                {% endif %}
                <a href="{{ url_for('.followers', username=user.username) }}">Followers: <span class="badge">{{ user.followers.count() - 1 }}</span></a>
                <a href="{{ url_for('.followed_by', username=user.username) }}">Following: <span class="badge">{{ user.followed.count() - 1 }}</span></a>
                {% if current_user.is_authenticated and user != current_user and user.is_following(current_user) %}
                | <span class="label label-default">Follows you</span>
                {% endif %}
        </p>

        {% if user == current_user %}
        <a class="btn btn-default" href="{{ url_for('main.edit_profile') }}">
            Edit Profile </a>
        {% endif %}
      </div>

        <br><br>
        <div>
                {{ ckeditor.load() }}

            {% if user == current_user %}
            {{ wtf.quick_form(form) }}

            {% endif %}

            {% block scripts %}
            {{ super() }}
            {{ pagedown.include_pagedown() }}
            {% endblock %}
        </div>

    </div>
    <ul class="posts">
    {% for post in posts %} 
    <li class="post">
        <div class="post-thumbnail">
        <a href="{{ url_for('.user', username=post.author.username) }}">
        <img class="img-rounded" src="{{ post.author.gravatar(size=40) }}">
        </a> 
        </div>
        <div class="post-date">{{ moment(post.timestamp).format('YYYY-MM-DD HH:mm:ss') }}</div>
                 <div class="post-author">
                     <a href="{{ url_for('.user', username=post.author.username) }}">
                         {{ post.author.username }}
                    </a>
                 </div>
                  <div class="post-body">
                    {% if post.body_html %}
                    {{ post.body_html | safe }}
                    {% else %}
                    {{ post.body }}
                    {% endif %}
                  </div>
                    
                    {% if post.author_id|int == current_user.get_id()|int %}
                    <form action="{{ url_for('main.delete_post', username=post.author.username) }}" method="post" class="delete-entry">
                        <input type="hidden" name="post_id" value="{{ post.id }}">
                        <input type="submit" value="Delete" />
                    </form>
                    {% endif %}
                <br>
    </li>
    {% endfor %}
    </ul>
    <div class="pagination">
        {{ macros.pagination_widget(pagination, '.user', username=user.username) }}
    </div>
    
{% endblock %}

wdls/templates/user_entries.html
{% extends "user_layout.html" %}
{% block body %}
  {% if session.logged_in %}
    <form action="{{ url_for('main.add_entry') }}" method="post" class="add-entry">
      <dl>
        <dt>Title:
        <dd><input type="text" size="30" name="title">
        <dt>Text:
        <dd><textarea name="text" rows="5" cols="40"></textarea>
        <dd><input type="submit" value="Share">
      </dl>
    </form>
  {% endif %}
  <ul class="entries">
  {% for entry in entries %}
    <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}<h5>{{ entry.times }}</h5></li>
      <form action="{{ url_for('main.delete_entry') }}" method="post" class="delete-entry">
          <input type="hidden" name="entry_id" value="{{ entry.id }}">
          <input type="submit" value="Delete" />
      </form>
  {% else %}
    <li><em>Unbelievable.  No entries here so far</em></li>
  {% endfor %}
  </ul>
{% endblock %}